sonar-project.properties

- Set the sonar.python.version to 3.8 and 3.9 to obtain a more detailed
analysis.

Set the python version in sonar-project.properties

---

docs/topics/principles.md

- Adjust ordered list delimiter from ) to . (see https://www.markdownguide.org/basic-syntax/#ordered-list-best-practices ), currently this is not picked up correctly by the documentation side generator, see https://deltares.github.io/HYDROLIB-core/topics/principles/#in-detail .

Adjust ordered list in principles.md

---

hydrolib/core/io/ini/parser.py
tests/io/test_ini.py

Fix float parser: only find-replace D/E in values, not in keys

---

hydrolib/core/io/structure/models.py
tests/io/test_structure.py

Moved all the weir tests to TestWeir class to keep them bundled.
Made the  `allowedFlowDir` optional and added the default `both`
Added a test for the default fields.

#77 Improve validation of optionally required fields in weir structure

---

hydrolib/core/io/bc/models.py
hydrolib/core/io/ini/models.py
tests/io/test_bc.py

Adjust the datablock type from `List[List[float]]` to `List[List[Union[float, str]]]` such that string values are also properly parsed, but float values are preferred.
Fixes #137

Adjust datablock type of DataBlockINIBasedModel

---

pyproject.toml

#204: Avoid Pydantic 1.9.x as long as List[Union[]] types are unsupported

---

hydrolib/core/basemodel.py
hydrolib/core/io/crosssection/models.py
hydrolib/core/io/ini/models.py
hydrolib/core/io/mdu/models.py
hydrolib/core/io/structure/models.py
tests/data/reference/bc/test.bc
tests/data/reference/fm/serialize_roughness.ini

Fixes #211.
* Any Pydantic BaseModel subclass can now optionally add a `Field(.., delimiter="..")` argument if a particular ModelField has a non-standard delimiter
* Added BaseModel helper function `get_list_field_delimiter`, which gets either the custom list delimiter for that field, or the default list delimiter of the model class (or the first parent class above it that defines it)
* IniBasedModel defines the main default delimiter=" "
* structure, crosssection and mdu submodels now have a custom list delimiter for a few of their fields.
* Some reference test files had to be updated, because they were using wrong list separators.

#211: Add configurable list delimiter symbol at Field and model level

---

hydrolib/core/io/structure/models.py
tests/io/test_structure.py

Fixes #214.
* serialization now hides all location fields, thanks to improved _exclude_fields
* I've prepared improved validation upon parsing, but left the code commented out, because the D-HYDRO Suite 1D2D currently still writes branchId+chainage for compounds (but this will have to change)
* also added extra unit test for the compound reading.

ignore location fields for compound type structures

---

hydrolib/core/io/bc/models.py
hydrolib/core/utils.py

223 dimr rainfallrunoffmodel fmmodel are not read

---

.devcontainer/devcontainer.json
Dockerfile
docs/guides/devcontainers.md

- Simplify the Dockerfile to only install poetry and other dependencies in the devcontainer
- Extend the devcontainer to run the `poetry install` command after creation of the environment
- Update the devcontainer documentation
Fixes #230

chore(devcontainer): fix docker devcontainer behaviour

---

hydrolib/core/io/rr/topology/models.py

Add modeltype 21 to RR node for open water preciptation/evaporation

---

hydrolib/core/basemodel.py
hydrolib/core/io/ini/parser.py
hydrolib/core/io/ini/serializer.py
hydrolib/core/io/mdu/models.py
tests/data/reference/fm/serialize_initialFields.ini
tests/data/reference/fm/serialize_roughness.ini
tests/io/test_ini.py

#104: Skip serialization of empty INI properties when configured

---

hydrolib/core/dflowfm/polyfile/serializer.py
tests/data/input/dflowfm_individual_files/test.pli
tests/data/input/test.pli
tests/dflowfm/test_polyfile.py

462: fix polyline serializer to print empty trailing comment lines

---

hydrolib/core/dflowfm/mdu/models.py
tests/data/input/dflowfm_individual_files/special_3d_settings.mdu
tests/data/reference/fm/special_3d_settings.mdu
tests/dflowfm/test_mdu.py

474: Add support for 3D z-sigma settings in MDU

---

hydrolib/core/dflowfm/ini/models.py
tests/data/reference/fm/special_3d_settings.mdu

#527: MDU keywords such as 1d2dLinkFile are written to file without comments

---

hydrolib/core/dflowfm/xyn/models.py
hydrolib/core/dflowfm/xyn/parser.py
tests/dflowfm/test_xyn.py

Add support for station names surrounded by double quotes

---

hydrolib/core/dflowfm/extold/models.py

I added all quantities from [ec_provider.F90](https://git.deltares.nl/oss/delft3d/-/blob/main/src/utils_lgpl/ec_module/packages/ec_module/src/ec_provider.F90#L2478-2615) that were missing in hydrolib-core in this PR. I have also added three new quantities that will be implemented in the linked [UNST-6593](https://issuetracker.deltares.nl/browse/UNST-6593)

feat: add missing oldext quantities

---

hydrolib/core/dflowfm/ini/models.py
hydrolib/core/dflowfm/ini/parser.py
tests/dflowfm/ini/test_ini.py
tests/dflowfm/ini/test_models.py
tests/dflowfm/test_storagenode.py

#559: Ensure only floats check for Fortran scientific notation when parsing

---

hydrolib/core/basemodel.py
hydrolib/core/utils.py
tests/test_basemodel.py
tests/test_utils.py

#354 
Im not fully sure how the @contextmanager functions.
It seems to create new instance for caching for each model which is initialized.
I could not setup a good test to test these steps:
Reading a file --> updating and changing the model it is read to --> saving the file --> reading the same file, changed data is read, since the file has been updated while the application is running.
Since there is not any other way to read the file as a user except for via the ctor.
The _load method could be used, but this is "private" and should not be used by the user.
This method also does not make use of the caching.

feat: reduce rereading cached files during init

---

hydrolib/core/dflowfm/bc/models.py
tests/data/reference/bc/t3d_backwards_compatibility.bc
tests/data/reference/bc/test.bc

bug: Updated alias from blockFrom and blockTo to block-From and block-To

---

hydrolib/core/dflowfm/mdu/models.py
tests/data/reference/fm/special_3d_settings.mdu

Updated default (-1) was discussed with @arthurvd and the default value in the FM user manual was also updated

chore: correct mdu.geometry.stretchtype default value

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/docs_release.yml
.github/workflows/integration.yml
.github/workflows/release.yml
docs/guides/contributing.md
docs/guides/setup.md
poetry.lock
pyproject.toml
sonar-project.properties

Steps:
- updated minimal python version to 3.9
- fixed netcdf4 dependency since 1.7.2 was excluded but should be supported (only 1.7.0 and 1.7.1 are yanked)
- updated ci.yml to avoid node.js warnings as in https://github.com/Deltares/HYDROLIB-core/actions/runs/11434993105
- removed 3.8 from tests/ci
- updated docs

chore: drop python 3.8 support

---

hydrolib/core/basemodel.py
hydrolib/core/dflowfm/t3d/models.py
hydrolib/core/dflowfm/tim/models.py
hydrolib/tools/extforce_convert/main_converter.py
pyproject.toml

The `exclude_unset=True` made some testcases fail. Remove this option and re-enable testcases.
Fixed the failing save model for t3d. 
- Set the default value for VECTORMAX to None see issue #756 
- Removed the `exclude_unset=True` in `ParsableFileModel._save`
- Fixed issue with `TimModel` for str or Path typing by using a `Union[str, Path]`
- Fixes #804

Remove exclude unset option from _save method

---

hydrolib/tools/extforce_convert/main_converter.py
hydrolib/tools/extforce_convert/mdu_parser.py
pyproject.toml
tests/tools/test_converter_boundary_condition.py
tests/tools/test_converters_source_sink.py
tests/tools/test_main_converter.py
tests/tools/test_mdu_parser.py

- Move the mdu file functionalities to the `mdu_parser` module.
- Save the `ExtModel` recursively only if it has any quantities, to avoid re-writing the .bc files that are already in the new format and did not need to be read or re-written.
- Remove the functionalities related to the `LegacyFMModel`.
- closes #812

Task/812-Refactor the MDU functionalities

---

hydrolib/core/dflowfm/crosssection/models.py
pyproject.toml
tests/dflowfm/test_crosssection.py

- The `CrossLocModel` accepts only a list of `CrossSection` and there are cases where only one `CrossSection` can be provided to instantiate the `CrossLocModel`
- The solution was to create a pre validator to convert any given values for the `crosssection` attribute into a list.
- Making the `crosssection` attribute as `Untion[CrossSection, List[CrossSection]]` was going to make the attribute value either a single cross section or a list therefore the the user would always have to check the type of the attribute value. and hence this solution was not considered.
- No no matter how may values is the given `crosssection` values it will always be a list type.
- Fixes #680

Extend CrossLocModel to accept one cross-section
