hydrolib/core/io/ini/util.py
hydrolib/core/io/mdu/models.py
tests/test_utils.py

Added crsfile and obsfile to split.

---

hydrolib/core/io/ini/parser.py
tests/io/test_ini.py

Support hashed string values in ini properties

---

hydrolib/core/basemodel.py
hydrolib/core/io/bc/models.py
hydrolib/core/io/dimr/models.py
hydrolib/core/io/ext/models.py
hydrolib/core/io/ini/models.py
hydrolib/core/io/net/models.py
hydrolib/core/io/net/writer.py
hydrolib/core/io/structure/models.py
tests/io/test_bc.py
tests/io/test_structure.py
tests/test_model.py
tests/utils.py

Closes #133. See https://sonarcloud.io/project/issues?id=Deltares_HYDROLIB-core&resolved=false
I've resolved one smell as won't fix, the `Conventions` with a capital as netCDF attribute, as it is per convention.

Fixed all sonarcloud smells.

---

hydrolib/core/io/ini/models.py
hydrolib/core/io/structure/models.py
tests/io/test_structure.py

Add the GeneralStructure to structure/models.py

---

hydrolib/core/io/ini/parser.py
hydrolib/core/io/mdu/models.py
tests/data/input/e02/f101_1D-boundaries/c01_steady-state-flow/Boundary.ext
tests/io/test_ini.py

Fixes #147 partially (other 2 fixes of 3 in total are under #7 and #122).

#147 fix validation errors

---

hydrolib/core/io/dimr/models.py
tests/io/test_docker.py
tests/test_model.py

Fixed parsing and serialization of Control elements in DIMR.

---

hydrolib/core/io/ini/util.py
hydrolib/core/io/structure/models.py
tests/data/input/e02/c11_korte-woerden-1d/dimr_model/dflowfm/structures.ini
tests/io/test_structure.py

#76: fixed optionality of all pump fields + validators and unit tests.

---

hydrolib/core/io/crosssection/models.py
tests/io/test_crosssection.py

#205: Allow empty friction specification in all crossdef types

---

hydrolib/core/io/mdu/models.py
hydrolib/core/utils.py

217: extend to_key such that leading digits are removed from aliased fields.

---

poetry.lock
pyproject.toml

fix: updated dependencies.

---

docs/reference/obs.md
hydrolib/core/io/common/models.py
hydrolib/core/io/ext/models.py
hydrolib/core/io/ini/util.py
hydrolib/core/io/obs/models.py
mkdocs.yml
tests/data/input/dflowfm_individual_files/obsPoints_obs.ini
tests/io/test_ext.py
tests/io/test_obs.py

feat: add support for observation point ini file

---

hydrolib/core/io/mdu/models.py

#240: Fix the types of 4 fields in the MDU file

---

hydrolib/core/io/polyfile/models.py
hydrolib/core/io/polyfile/parser.py
hydrolib/core/io/polyfile/serializer.py
tests/data/input/test.pli
tests/io/test_polyfile.py

#301: Ensure poly files can be saved

---

hydrolib/core/io/structure/models.py

After discussion with Arthur, added make_list_validator to StructureModel, to support a single structure in structure.ini file

Put single structure in list in StructureModel class

---

hydrolib/core/io/ext/models.py

changed type of xCoordinates and yCoordinates from int to float

Change type of xcoordinates and ycoordinates in Lateral class from int to float.

---

hydrolib/core/io/ext/models.py
hydrolib/core/io/net/writer.py
tests/io/test_net.py

Net writer should not produce nan as fill values

---

hydrolib/core/io/mdu/models.py

AutoStart type should be int instead of bool, since 2 is also a allowed value according to the manual: https://content.oss.deltares.nl/delft3d/manuals/D-Flow_FM_User_Manual.pdf#section.A.1

Change AutoStart type from bool to int

---

hydrolib/core/io/bc/models.py
hydrolib/core/io/ini/util.py
tests/io/test_bc.py

Fix backward compatible enum values via validator

---

hydrolib/core/io/dflowfm/bc/models.py
hydrolib/core/io/dflowfm/ini/models.py
tests/data/reference/crosssection/crsloc.ini
tests/io/dflowfm/test_bc.py
tests/io/dflowfm/test_crosssection.py

Enums are incorrectly written to files

---

docs/tutorials/loading_and_saving_a_model.md
hydrolib/core/basemodel.py
tests/test_basemodel.py
tests/test_model.py

#355: Add support for non-recursively loading models

---

hydrolib/core/io/dflowfm/bc/models.py
tests/io/dflowfm/test_bc.py

Small refactoring of the VectorQuantityUnitPairs and VectorForcingBase

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/docs_release.yml
.github/workflows/integration.yml
poetry.toml

#454: Update poetry image and poetry version to latest in CI

---

hydrolib/core/basemodel.py
tests/test_basemodel.py

Support for str besides Path

---

docs/reference/xyn.md

Added missing documentation for the .xyn file

---

hydrolib/core/dflowfm/__init__.py

Publicly expose the new XYN classes

---

hydrolib/core/dflowfm/polyfile/parser.py
tests/dflowfm/test_polyfile.py

Fix ignorance of trailing data on polyline data lines

---

hydrolib/core/dflowfm/extold/models.py
tests/dflowfm/test_extold.py

Related to issue #535.
Partially resolves the issue.

#535: Add the quantity `nudge_salinity_temperature` to ext old file header

---

hydrolib/core/dflowfm/research/models.py

feat: Fix remaining keywords

---

hydrolib/core/dflowfm/research/models.py
tests/dflowfm/test_research.py

feat: Make research wave section optional again.

---

hydrolib/core/dflowfm/research/models.py

feat: Move jadelvappos to physics section.

---

hydrolib/tools/extforce_convert/converters.py

Added underscore after file stem for glob of files.

Fix: quantity file discovery with _ after stem.

---

tests/tools/test_cmp_to_bc.py
tests/tools/test_tim_to_bc.py
tests/utils.py

- Extend the functionalities in the `compare_two_files` function that is used to compare the content of two files to search for specific lines in the file based on a regex expression  and to ignore them.
- Fixes #818

remove hard coded version

---

tests/test_basemodel/test_basemodel.py
tests/test_basemodel/test_model_treet_raverser.py

- Add unit tests for the `ModelTreeTraverser` class methods.
- Fixes #823 

unit test the `ModelTreeTraverse`.

---

hydrolib/core/dimr/models.py
hydrolib/core/dimr/parser.py
hydrolib/core/dimr/serializer.py
pyproject.toml
tests/test_model.py

refactor dimr functionalities

---

.github/workflows/integration.yml

- Update the docker hub job version.
- Fixes #814
- The ci does not give the warning anymore.

update fm_container CI pipeline deprecated syntax

---

hydrolib/core/dflowfm/polyfile/models.py
hydrolib/core/dflowfm/polyfile/parser.py
hydrolib/core/dflowfm/t3d/models.py
hydrolib/core/dflowfm/tim/models.py
hydrolib/core/dflowfm/xyn/models.py
hydrolib/core/dflowfm/xyn/serializer.py
hydrolib/core/dflowfm/xyz/models.py
hydrolib/core/dflowfm/xyz/serializer.py
tests/dflowfm/polyfile/test_polyline_models.py
tests/dflowfm/t3d/test_t3d.py
tests/dflowfm/test_tim.py
tests/dflowfm/test_xyn.py
tests/dflowfm/test_xyz.py

Migrated working model changes from the old branch to a new branch and merge to new branch.
List of updated models that function currently:
polyfile
t3d
cmp
tim
xyn
xyz
- Excisting tests for these models function correctly.

Migrate working models from old pydantic v2 branch

---

hydrolib/core/dimr/models.py
tests/test_model.py

remove exception for fmcomponent.process==1

---

.github/workflows/release.yml
docs/guides/contributing.md

release workflow

---

hydrolib/tools/extforce_convert/mdu_parser.py
tests/tools/test_mdu_parser.py

new external forcing files names 

---

hydrolib/tools/extforce_convert/converters.py
tests/tools/test_converters_source_sink.py

Bugfix: Write the area to the new extforcefile for SourceSink forcing

---

poetry.lock
pyproject.toml

updated meshkernel min version and lockfile

---

hydrolib/core/base/file_manager.py

replaced if with elif

---

poetry.lock
pyproject.toml

add pyyaml
